name: build

on:
  push:

jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - cisTEM
          - ctffind
          - relion
          - TEM-simulator
    steps:
      - uses: actions/checkout@v5

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org?priority=41 
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - run: nix build --print-build-logs --impure .#packages.x86_64-linux.${{ matrix.package }}
        env:
          NIXPKGS_ALLOW_UNFREE: "1"
